### ISSUE TITLE
Firefox 45 (desktop) support?

### ISSUE THREAD

**Issue by RichardD2** [mdn/web-speech-api#1]
The synthesis demo doesn't work in FF45 (64-bit) on Windows 10, even after changing the flag in `about:config`. The `getVoices` method returns an empty array.

**Comment by HarveyWilliams** [comment]
I can second this.

**Comment by chrisdavidmills** [comment]
There is some kind of bug going on in 45 in that case, but it looks like it works in 64-bit Nightly on Windows 10. I just tried it. So it should filter down to the release version soon.
