### ISSUE TITLE
Get the result in percentage rather than TRUE or False ?

### ISSUE THREAD

**Issue by jattnet** [mdn/web-speech-api#11]
HI Guys

I am happy to see your work ,  I am using your API , specially 
Phrase making , It work like a Charm for me.

As per analysis and test I can see the result is Either true or false.
**Now is there any method exist that can help me to get the result in percentage ?**

e.g 
the text to speech is : Hi how are you ?
and user said  : Hi how are we ?

So the result will be in the percentage that , the text is 70%correct  ?...

I hope you following me. 

I need to build a Pronunciation website....

**Comment by ctsstc** [comment]
Hi, @jattnet this repository isn't the one who's created the API, the API is provided via your browser, and implemented on a per-browser basis trying to follow the [w3.org specifications](https://dvcs.w3.org/hg/speech-api/raw-file/tip/webspeechapi.html)

You would have to write some code to check that. You could try splitting the strings by spaces and see how well they match up, as a quick and dirty method (or even parse the lines character by character). Some caveats to that method would be that an offset near the beginning could make all words after it look incorrect, so this quickly starts to become more complicated than my quick initial example.

**Comment by chrisdavidmills** [comment]
There is a measure provided that gives you this:

https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognitionAlternative/confidence

I've never tried t use it though, so I don't have accurate or well-supported it is.

**Comment by schalkneethling** [comment]
Hey @jattnet! Thank you for opening this issue. We are combining some of our repositories to enable us to triage pull requests and issues more effectively. Therefore, this specific repository will be merged into the more prominent [dom-examples](https://github.com/mdn/dom-examples) repository. Please also see Chris' comment above.
