### ISSUE TITLE
Phrase matcher says that matching have failed, but it doesn't

### ISSUE THREAD

**Issue by vasilii-kovalev** [mdn/web-speech-api#27]
Hello!
Am I wrong or matching was correct? Nevertheless, I can see this message sometimes:
![image](https://user-images.githubusercontent.com/10310491/44302971-08c10480-a33d-11e8-84ea-a617df9d0ae5.png)
Maybe it's because of I/i (upper/lower case of the first letter)?

**Comment by bohnacker** [comment]
I had the same problem. 
@vasilii-kovalev: You're right, it's because of the I/i in the beginning. Converting the speechResult to lowerCase as well will fix the problem.
`var speechResult = event.results[0][0].transcript.toLowerCase();`

**Comment by chrisdavidmills** [comment]
This is now fixed. Thanks @bohnacker
