### ISSUE TITLE
Chrome 69

### ISSUE THREAD

**Issue by liyokuna** [mdn/web-speech-api#28]
Hello,

I working on a text to speech using your Speech Synthesis.
I have built a button to put on pause when speechSynthesis is speaking but each time I click on that button, nothing happened. When I go deep on chrome console, i found this messages

> [Exception: TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them at Function.remoteFunction (<anonymous>:2:14)]

Here is an image
![capture](https://user-images.githubusercontent.com/11217936/46679291-f188ef80-cbe6-11e8-9d1c-e1476dd7e6a9.PNG)

**Comment by liyokuna** [comment]
And on Firefox, the language list is limited to Microsoft whereas on chrome we have a bunch of languages.
Is that normal ?

**Comment by chrisdavidmills** [comment]
Hi there @liyokuna ! Have you got a version of your code online that I can look at? I'm not 100% sure what is causing the error, but I'd be glad to have a play and try to figure it out.

For the language list, the browser generally gets the available languages from the speech synthesis features available on the underlying platform, so I'd have thought they'd be the same. Interesting.

**Comment by liyokuna** [comment]
Hello @chrisdavidmills do you have time to check my project ?

**Comment by chrisdavidmills** [comment]
Hi there! Sorry for the delay; I got really busy last week.

This is a really great bit of code! I am trying to understand exactly what is wrong with it — when I tried it in Chrome on macOS, the pause button worked perfectly, and I got no errors. Makes me wonder if this is a platform-specific problem? I am assuming you are on Windows from what you said above?

And yes, I get some extra languages on macOS too — Chrome seems to add in some of its own.

**Comment by liyokuna** [comment]
ah ah! yeah dev fam !
Yes I am using Windows. That's my biggest fear, stuff working on MacOS and not well on Windows OS and vice versa. But weirdly, it was working on chrome, the only thing that changes is the update made in September ( moving chrome from 68 to 69). I will try on chrome 68 ( if i download one).
Chrome added some languages of its own but on Mozilla we only have one language. So the function getLangaues depends on the browser.
did you plan that in your work or was it just unexpected ?
ok let me know.

**Comment by chrisdavidmills** [comment]
Our implementation hasn't been worked on for a while. Your example didn't seem to work for me in Firefox; just Chrome.

Yes, extra languages added on top of the operating system defaults will depend on the browser.

If you still get trouble in Windows, maybe file a bug against Chromium?

**Comment by liyokuna** [comment]
ok !
I will report a bug issue to chromium.
On mozilla it's working. That's not the case for me. I can set on pause but the resume. I'll work on it again.
If I face a weird behaviour, I'll let you know

**Comment by liyokuna** [comment]
I also try on a mac computer and it's not working :/. weird !

**Comment by liyokuna** [comment]
Hello @chrisdavidmills, i created a bug issue in chromium community.
Iwas playing around, I take this [examples ](https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesis/pause#Examples)and added in my project.
And it was enabled to set it-self on pause.
I am wondering if that function have a problem...

**Comment by liyokuna** [comment]
Hi !
I create an [issue](https://bugs.chromium.org/p/chromium/issues/detail?id=911164&can=2&start=0&num=100&q=&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified&groupby=&sort=) on the chromium team.

**Comment by liyokuna** [comment]
Hi ! @chrisdavidmills 
I don't get why the pause function doesn't work on chrome but works on Mozilla.
I have few question, you said on mozilla language are added but mozilla on its own.
How can we get more languages ?

**Comment by chrisdavidmills** [comment]
I don't know much about the Chrome implementation; the Synthesis stuff works in Firefox fairly well as far as I know, but I've not looked at this for a while.

When you say "languages", I'm assuming you mean "voices"? The browser basically grabs the voices avaiable on the operating system (and in Chrome's case, also imports some of its own). To get more languages you'd have to find a way of installing more on the operating system, so, create your own, install more default ones, or get some third party voices.

You can for example get more voices on macOS in System Preferences > Accessibility > Speech > System Voice > Customize.

There are some commercial third party ones here, for example: https://www.cereproc.com/en/storeosx

**Comment by justingolden21** [comment]
I know I'm a year late to the party, but I've experienced the same thing with Chrome. It seems like pausing the speech synthesis makes it completely unable to work, even after **the tab is closed** and even after **all Chrome tabs are closed**. I was only able to get it to work again after force closing Chrome, or after calling the cancel() function. One tab pausing one speech utterance shouldn't permanently turn it off for all tabs forever until Chrome is either completely restarted or someone cancels the request. Absolutely absurd.

**Comment by guest271314** [comment]
> I don't get why the pause function doesn't work on chrome but works on Mozilla.

Different implementations of Web Speech API specification. See https://github.com/web-platform-tests/wpt/issues/23097.

**Comment by schalkneethling** [comment]
Hey @liyokuna! Thank you for opening this issue. We are combining some of our repositories to enable us to triage pull requests and issues more effectively. Therefore, this specific repository will be merged into the more prominent [dom-examples](https://github.com/mdn/dom-examples) repository. Please open a new issue if you still feel that this issue is relevant. Thank you.
