### ISSUE TITLE
Firefox 49 look for webkitspeech

### ISSUE THREAD

**Issue by Mte90** [mdn/web-speech-api#3]
I get this error on firefox 49 also if i have enalbed in the config media.webspeech.recognition.enable:

```
ReferenceError: webkitSpeechRecognition is not defined
```

**Comment by kodiraj** [comment]
its not working for me either.

i tried firefox 49 in my mac.speech recongintion is not working.

Even the demo is not working

**Comment by Mte90** [comment]
I get also on firefox 50

**Comment by clemens-tolboom** [comment]
I tried using Firefox 48.x but that failed too. Has Firefox dropped support for SpeechRecognition?

```javascript
var SpeechRecognition = SpeechRecognition || webkitSpeechRecognition;
```

Checking my __about:config__ I have `media.webspeech.recognition.enable = true`

The demo http://mdn.github.io/web-speech-api/speech-color-changer/ is broken on Firefox but still works on Chrome

**Comment by clemens-tolboom** [comment]
Hmmm ... according to http://stackoverflow.com/questions/39784986/speechrecognition-is-not-working-in-firefox this is not yet working on FF

> And currently, you'll have to be in the chrome environment (extension) to use it.

See https://bugzilla.mozilla.org/show_bug.cgi?id=1248897

**Comment by clemens-tolboom** [comment]
I've voted for the [Bugzilla issue]( https://bugzilla.mozilla.org/show_bug.cgi?id=1248897)

**Comment by clemens-tolboom** [comment]
I work with the https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API using Chrome for a few weeks now. Glad this example exists :-)

**Comment by ctsstc** [comment]
This code that all the files uses should be more defensively coded so that if none are defined it defaults to false, and code added to gracefully present an error message that no speech/synch/recognition could be found.

```
var SpeechRecognition = SpeechRecognition || webkitSpeechRecognition
var SpeechGrammarList = SpeechGrammarList || webkitSpeechGrammarList
var SpeechRecognitionEvent = SpeechRecognitionEvent || webkitSpeechRecognitionEvent
```

**Comment by chrisdavidmills** [comment]
Yup, in a real app you would do this. But this is just a demo so I didn't bother ;-)

I'll make sure the readme has a note about this and what the current state of browser support is.

Thanks for the interest folks. I'm really sad that we still don't have speech recognition enabled in Fx. We did have it briefly in Firefox OS, before it got killed.

**Comment by ctsstc** [comment]
I kind of figured that it's slim for a reason, it is a demo and has a very narrow support currently (cross browser testing changes would be useless :P)

**Comment by Mte90** [comment]
I have the same error also on Firefox Nightly 57...
There are plans for the Firefox support?

**Comment by Sanchit-20** [comment]
Webspeech recognition is not running in Mozilla Firefox 57.0.1

**Comment by chrisdavidmills** [comment]
Yup, we still don't support this. I have had some vague hints that we might see movement on this in 2018, but nothing definite.

**Comment by ilgun** [comment]
Is there any update or workaround for this one?

**Comment by clemens-tolboom** [comment]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1248897 for progress.

Currently http://mdn.github.io/web-speech-api/speech-color-changer/ is not working on my Chrome either. Maybe it's http and not https?

**Comment by clemens-tolboom** [comment]
Yep changing this to https://mdn.github.io/web-speech-api/speech-color-changer/ fixed it on Chrome.

**Comment by ilgun** [comment]
Thanks @clemens-tolboom

**Comment by christian212519** [comment]
Hey guys, apologies for not getting back to you sooner.  Basically, the reason your not able to access your microphone is due to a security issues mostly all browsers enforce.  That being, if you try to run a file wile the initial extension file:///, it will refuse to give access to your microphone, Hence, this program will never work in that instance.  However, if you do want to see this program work, simply copy and paste the html, js, and css into your preferred IDE and run it from there.  It will operate under a local host which your browser will accept and give access to your microphone.  Hope this helps!

**Comment by dibujohn** [comment]
Hi All, 
I got a working solution like following.

    var SpeechRecognition = this.SpeechRecognition || this.webkitSpeechRecognition;
    var SpeechGrammarList = this.SpeechGrammarList || this.webkitSpeechGrammarList;
    var SpeechRecognitionEvent = this.SpeechRecognitionEvent || this.webkitSpeechRecognitionEvent;

Please consider this solution.

**Comment by Mte90** [comment]
So in Firefox not the speechrecognition is avalaible?

**Comment by chrisdavidmills** [comment]
> So in Firefox not the speechrecognition is avalaible?

It is not available, no. It was available briefly in Firefox OS, just before "the end". AFAIK, it is being worked on, but I've not heard anything for a while.

**Comment by IshanFx** [comment]
Still not support for FF 66?

**Comment by pervezalam83** [comment]
Still not supported for FF 78

**Comment by UjjwalPandey** [comment]
Still not supported in FF 79

**Comment by Naveen-KumarG** [comment]
Still not supprted in FF v96

**Comment by clemens-tolboom** [comment]
See https://caniuse.com/speech-recognition for supporting browsers and https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition#browser_compatibility (FF is all read)

### Safari

I tried Safari (Version 15.2 (16612.3.6.1.8, 16612)) and Safari TP (Release 139 (Safari 15.4, WebKit 16613.1.14.41.2))

In Chrome this works

```javascript
var SpeechRecognition = SpeechRecognition || webkitSpeechRecognition
```

but Safari needs

```javascript
var SpeechRecognition = SpeechRecognition || webkitSpeechRecognition ||
      window.webkitSpeechRecognition;
```

Regarding events I'm still puzzled with Safari so stick to Chrome and hoping FF will get there too.

**Comment by schalkneethling** [comment]
Hey! Thank you for opening this issue. We are combining some of our repositories to enable us to triage pull requests and issues more effectively. Therefore, this specific repository will be merged into the more prominent [dom-examples](https://github.com/mdn/dom-examples) repository. Please open a new issue if you still feel that this issue is relevant. Thank you.
