### ISSUE TITLE
Is there a way to know when the speak method finished talking.

### ISSUE THREAD

**Issue by JanikSachs** [mdn/web-speech-api#31]
Hey everyone just asking myself if it is possible to know if the speak function is done.
With best regards.

**Comment by JanikSachs** [comment]
I found something https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisUtterance/onend

**Comment by Phe0nix** [comment]
Yeah with onend() method you can do that. but onend() means recording is end not only the speech. 
But if you want to get the result after end of the speech not recording, then uses onspeechend() method.
