### ISSUE TITLE
Web Speech Recognition Firefox Problem

### ISSUE THREAD

**Issue by Phe0nix** [mdn/web-speech-api#33]
Hi, 
I'm trying to build an speech email sender with the help of Speech Recognition.
First draft is complete. Link - [Speech Email Sender](https://phe0nix.github.io/Speech-Email-Sender/)

It's working fine on chrome but the problem is for firefox, i used the flag that mentioned on mdn and also enable the config setting but still recording notification not coming for allowing the web speech.

Is there anything settings i have to do for make it work?

**Comment by chrisdavidmills** [comment]
Speech recognition hasn't worked in Firefox for a long time. It did work in Firefox OS and Firefox Desktop briefly, but it was removed again. 

I updasted the aupport data in the references a while ago, but I see it still said Firefox was supported in https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API/Using_the_Web_Speech_API. I have updated that now, so hopefully no more confusion.

Sorry about that.
