### ISSUE TITLE
SpeechSynthesisUtterance stops in between for Italian language !!

### ISSUE THREAD

**Issue by SunnySv72** [mdn/web-speech-api#37]
**Environment Information :** 
_OS- Windows 10 Pro
Browser - Chrome Version 74.0.3729.169_  

On trying to have this particular text:

`Alice stava cominciando ad essere molto stanca di sedersi accanto alla sorella sulla riva e di non avere niente da fare una o due volte che aveva sbirciato nel libro che sua sorella stava leggendo ma non aveva immagini o conversazioni al suo interno`

to speak using SpeechSynthesisUtterance, the speech stops abruptly at the last word `interno`. it just pronounces `int` and the rest of the text gets ignored.
This happens to any other word, just the first two-three words  characers out of the last word get spoken.
It's not because of the character limit of utterance as it is much less than the defined limit i.e. 500 chars.
English, on the other hand, works all right but facing issues similarly for languages like Hindi.
It is to note that
- _This issue occurs only on Chrome_
- _Italian and Hindi are both **browser-native** languages in Chrome for the Speech Synthesis API_
- The **OnEnd** callback also does not fire when the same happens.

**Comment by tomByrer** [comment]
Do you have examples of other apps that do work for Italian in Chrome?

**Comment by schalkneethling** [comment]
Hey @SunnySv72! Thank you for opening this issue. For questions such as this, we would recommend StackOverflow as you are likely to get a faster response to your question. Also, note that we are combining some of our repositories to enable us to triage pull requests and issues more effectively. Therefore, this specific repository will be merged into the more prominent [dom-examples](https://github.com/mdn/dom-examples) repository.
