### ISSUE TITLE
Record audio file while doing speech recognition

### ISSUE THREAD

**Issue by ManishTiwari-cloud** [mdn/web-speech-api#41]
Hi All,

I am working on speech recognition (speech to text) functionality on our website. For this, I also need to capture user’s audio (mp3, wav or any audio file format) as well. 

Currently, I am doing speech recognition is using webkitSpeechRecognition (https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition) but I don’t see anything in this to also return audio file of voice.

On desktops, I am able to overcome this by using MediaRecorder (https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder) which internally calls getUserMedia but on tablets, this doesn’t work as it either allows me to do speech recognition or record mic for audio. 

Question - Is there any interface in webkitSpeechRecognition which will also give me audio file along with recognized text so I don’t have to use MediaRecorder?  

If not, is this in a road map to add it?

Thanks in advance.

**Comment by PeterNelsonT** [comment]
Is there any workaround in mobiles?
