### ISSUE TITLE
Change VoiceGender To Female

### ISSUE THREAD

**Issue by desawarna** [mdn/web-speech-api#43]
How to Change VoiceGender To Female ?
thank :smile_cat:

**Comment by sesamechicken** [comment]
This is old, but you can simply use the `getVoices()` method on the `speechSynthesis` instance. For an array of all available voices, you could do:

```js
const synth = window.speechSynthesis;
const voiceArray = synth.getVoices(); // returns array of voice objects
```

Hope this helps!
