### ISSUE TITLE
Fails to trigger the onresult callback in Chrome Android .

### ISSUE THREAD

**Issue by reltronx** [mdn/web-speech-api#47]
I had been trying to make the web speech API work in one of my react projects. The API works fine in Chrome Desktop ( Version 83.0.4103.97  ), But in Chrome Android ( Version 83 ) the onresult callback doesn't get called.

The expected sequence of callbacks should have been:= 
1) onstart 
2) onspeechstart
3) onresult
4) onspeechend
5) onend

Running this demo in mobile ( Android ) fails as well .

**Comment by schalkneethling** [comment]
Hey @reltronx! Thank you for opening this issue. For a question such as this, you might get a faster response using a site such as StackOverflow. Also, note that we are combining some of our repositories to enable us to triage pull requests and issues more effectively. Therefore, this specific repository will be merged into the more prominent [dom-examples](https://github.com/mdn/dom-examples) repository. Thank you.
