### ISSUE TITLE
How recognition.continuous really works?

### ISSUE THREAD

**Issue by Varsha-Rao** [mdn/web-speech-api#49]
I'm trying to understand the logic behind how the continuous feature of recognition really works behind the scenes. I have a kaldi decoder but I want to code the same logic of automatically recognizing words as soon as there's a pause from the user just like web speech API's continuous feature allows. How is this really working? 

Does the recognizer start decoding after a few seconds and if so how many seconds? Or does its recorder have the ability to differentiate when it is getting some form of input and when it's not? If so, does it consider background noise to be user's silence and perform a decoding? There has to be a recorder and recognizer as two separate entities. If it's not, then how do they work as a single entity?

**Comment by schalkneethling** [comment]
Hey @Varsha-Rao! Thank you for opening this issue. Have you looked at https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition/continuous? Also, perhaps having a look at the [specification](https://wicg.github.io/speech-api/#dom-speechrecognition-continuous) could help shed some light? Another place to post this question might be StackOverflow.

Also, note that we are combining some of our repositories to enable us to triage pull requests and issues more effectively. Therefore, this specific repository will be merged into the more prominent [dom-examples](https://github.com/mdn/dom-examples) repository. Thank you.
