### ISSUE TITLE
Any update on iOS Safari, Chrome and Firefox?

### ISSUE THREAD

**Issue by vatsa287** [mdn/web-speech-api#50]
SpeechRecognition API works seamlessly on desktop platforms ( haven't tested on Android ) but not currently working on iOS browsers. Any update regarding this issue?

**Comment by AoDev** [comment]
It works for me in Android but I can not find a way to make it work on iOS (13).
I also have a [stackoverflow question](https://stackoverflow.com/questions/67184474/are-there-requirements-in-the-iphone-ios-settings-for-html5-speech-synthesis-t) open about it.
