### ISSUE TITLE
Chrome Mobile 86 won't change of language in the TTS demo

### ISSUE THREAD

**Issue by Ratatinator97** [mdn/web-speech-api#51]
Hello,

On Chrome mobile (Android 10, Chrome version: 86.0.4240.99) the [Speak easy synthesis demo](https://mdn.github.io/web-speech-api/speak-easy-synthesis/) won't change of language. It can only speak in the default language of the OS.
The issue happens only on Chrome Mobile !

Best regards,
Alex

**Comment by JorgeMadson** [comment]
I got the same issue, now the `window.speechSynthesis.getVoices()` return a empty array `[]`

**Comment by JorgeMadson** [comment]
Now is working again
https://mdn.github.io/web-speech-api/speak-easy-synthesis/
