### ISSUE TITLE
Pause and play

### ISSUE THREAD

**Issue by meetmec12** [mdn/web-speech-api#52]
This is really nice but can we have a pause button ? And resume button  .

**Comment by schalkneethling** [comment]
Hey @meetmec12! We are combining some of our repositories to enable us to triage pull requests and issues more effectively. Therefore, this specific repository will be merged into the more prominent [dom-examples](https://github.com/mdn/dom-examples) repository. If you would like to contribute to this example and add the functionality you mentioned, please feel free to open a new issue once this repo is moved. Thank you.
