### ISSUE TITLE
Can I train a model so that it recognize better cities, (and only cities)

### ISSUE THREAD

**Issue by bacloud22** [mdn/web-speech-api#53]
Hi,
I am making a weather web app. I thought to bring web speech API will make the app more accessible, and I am already amazed by the confidence transcribing voice and very easily.
However, I know where there is a ML model there is a always a room for optimization. I would like to restrict it's transcription to only cities. It would be more focus, and hopefully more accurate. Is it possible to use a Tensorflow.js model for example ? has anyone done that ? 

thanks !

**Comment by schalkneethling** [comment]
Hey @bacloud22! For general questions like this, we would recommend using a site such as StackOverflow. Also, note that we are combining some of our repositories to enable us to triage pull requests and issues more effectively. Therefore, this specific repository will be merged into the more prominent [dom-examples](https://github.com/mdn/) repository. Thank you.
