### ISSUE TITLE
chrome version 90 window.speechSynthesis.speak(msg) is not work  

### ISSUE THREAD

**Issue by Liuyicong-git** [mdn/web-speech-api#54]
office live demo https://mdn.github.io/web-speech-api/speak-easy-synthesis/. is not work

**Comment by Liuyicong-git** [comment]
![461619274064_ pic_hd](https://user-images.githubusercontent.com/29158531/115964162-b147ad80-a555-11eb-9bf8-77e517cfeec3.jpg)

**Comment by Liuyicong-git** [comment]
![Uploading 451619274064_.pic_hd.jpg…]()

**Comment by Liuyicong-git** [comment]
![451619274064_ pic_hd](https://user-images.githubusercontent.com/29158531/115964214-efdd6800-a555-11eb-88ed-d80ce85d0164.jpg)

**Comment by 13100967125** [comment]
the same ,not work 
the code .......
if (synth.speaking) {
        console.error('speechSynthesis.speaking');
        return;
    }

**Comment by EasonLin0716** [comment]
same here. chrome 89.x, firefox, opera and edge all work fine

**Comment by Liuyicong-git** [comment]
In my project  ,  I have solved this problem .

**Comment by Liuyicong-git** [comment]
use cancel method

**Comment by 13100967125** [comment]
can you show me code ?

**Comment by Liuyicong-git** [comment]
https://stackoverflow.com/questions/67224912/speechsynthesis-speaking-api-is-not-fine-in-chrome-version-90

**Comment by 13100967125** [comment]
can you show me code demo ,see you page ,i find none

**Comment by Liuyicong-git** [comment]
you should use speechSynthesis.cancel() before you use speechSynthesis speaking . if you test MDN Demo , you can run code speechSynthesis.cancel() on console.

**Comment by EasonLin0716** [comment]
In chrome 90.x I found MDN Demo sometimes work but sometimes not, and I tried adding speechSynthesis.cancel() in my project but it still doesn't work as expected...

**Comment by abearxiong** [comment]
in windows, some chrome 90.x is working, some chrome 90.x is not working.

**Comment by 3529** [comment]
> https://stackoverflow.com/questions/67224912/speechsynthesis-speaking-api-is-not-fine-in-chrome-version-90

这个链接已经失效了，请问你是怎么解决的呢？
this URL has expired. can you tell me the resolve? thanks.

**Comment by ErrorBot1122** [comment]
this should not be closed, it is still broken...
