### ISSUE TITLE
'Network' error when trying to use SpeechRecognition

### ISSUE THREAD

**Issue by framilano** [mdn/web-speech-api#61]
It worked fine a month ago, I tried again today and I just get this 'network' error as a SpeechRecognitionErrorEvent.

Even the demo with colors doesn't work. Tried with Brave, Edge and Chromium.

**Comment by clemens-tolboom** [comment]
AFAIK it never worked on Chromium. I maybe wrong but using the code below in the console shows `error: 'network',` on Chromium.

```javascript
SpeechRecognition = window.webkitSpeechRecognition || SpeechRecognition || webkitSpeechRecognition
x = new SpeechRecognition()
x.onerror = ev => console.log(ev.type, ev)
x.onresult = ev => console.log(ev.type, ev)
x.onend = ev => console.log(ev.type, ev)
x.onstart = ev => console.log(ev.type, ev)
x.start()
```

On my own project: Edge works, Safari works (with its own quirks), Chrome works.

I do not see Brave on https://caniuse.com/?search=SpeechRecognition

**Comment by PROxZIMA** [comment]
`SpeechRecognition` uses Google service for recognition. Thus it requires `GOOGLE_API_KEY`, `GOOGLE_DEFAULT_CLIENT_ID` and `GOOGLE_DEFAULT_CLIENT_SECRET` keys as environment variables.

`Network` error means that the above keys are missing. Obviously these keys are missing in Firefox and chromium. As Google Chrome, Edge supports Google login, they have the above keys.

**Comment by clemens-tolboom** [comment]
@PROxZIMA that is not true. Browser based speech recognition does not need these keys.

**Comment by PROxZIMA** [comment]
Ohh understandable. Thanks for correcting me

**Comment by schalkneethling** [comment]
> I do not see Brave on [caniuse.com/?search=SpeechRecognition](https://caniuse.com/?search=SpeechRecognition)

Brave is a Chromium-based browser so generally, if it works in Chrome it will work in Brave. They can, of course, decide to disable some features but in general, it is a 1:1.

**Comment by schalkneethling** [comment]
Hey @framilano! Thank you for opening this issue. We are combining some of our repositories to enable us to triage pull requests and issues more effectively. Therefore, this specific repository will be merged into the more prominent [dom-examples](https://github.com/mdn/dom-examples) repository. Please open a new issue if you still feel that this issue is relevant. Thank you.
